/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
<<<<<<< HEAD
  interface MyInput {
    'header': string;
=======
  interface MyFetch {
    'language': string;
>>>>>>> fetch-jest-mock
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
    'onButtonClicked'?: (event: CustomEvent<string>) => void;
  }
<<<<<<< HEAD
  interface MyInput extends JSXBase.HTMLAttributes {
    'header'?: string;
    'onThisHappened'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-input': MyInput;
=======
  interface MyFetch extends JSXBase.HTMLAttributes {
    'language'?: string;
  }

  interface ElementInterfaces {
    'MyComponent': Components.MyComponent;
    'MyFetch': Components.MyFetch;
  }

  interface IntrinsicElements {
    'MyComponent': LocalJSX.MyComponent;
    'MyFetch': LocalJSX.MyFetch;
>>>>>>> fetch-jest-mock
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
<<<<<<< HEAD
=======

  interface HTMLMyFetchElement extends Components.MyFetch, HTMLStencilElement {}
  var HTMLMyFetchElement: {
    prototype: HTMLMyFetchElement;
    new (): HTMLMyFetchElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'my-fetch': HTMLMyFetchElement
  }
>>>>>>> fetch-jest-mock

  interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {}
  var HTMLMyInputElement: {
    prototype: HTMLMyInputElement;
    new (): HTMLMyInputElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
<<<<<<< HEAD
    'my-input': HTMLMyInputElement;
=======
    'my-fetch': HTMLMyFetchElement;
>>>>>>> fetch-jest-mock
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

